version: '3.8'
services:
  backend:
    image: xiaole6324/meowarchive-backend:1.0.2
    container_name: backend
    ports:
      - 8000:8000
    networks:
      - meowarchive-net

networks:
  meowarchive-net:
    driver: bridge