create table "user"
(
    id               bigint generated by default as identity
        primary key,
    nickname         varchar(255),
    sex              smallint,
    description      varchar(255),
    doing            varchar(300),
    level            integer,
    avatar           varchar(320),
    collection_times integer,
    forked_times     integer,
    praise_times     integer,
    view_times       integer
);

create table board
(
    id            bigint generated by default as identity
        primary key,
    name          varchar(100),
    description   varchar(255),
    is_hot        boolean,
    n_posts       integer,
    n_discussions integer
);

create table posts
(
    id            bigint generated by default as identity
        primary key,
    ask_help_flag integer,
    board_id      integer
        constraint fk_board_posts
            references board,
    board_name    varchar(255),
    content       text,
    created_at    timestamp default now(),
    is_authorized boolean,
    is_featured   boolean,
    is_pinned     boolean,
    n_comments    integer,
    n_replies     integer,
    n_views       integer,
    title         varchar(255),
    tutorial_flag integer,
    updated_at    timestamp default now(),
    user_id       bigint
        constraint fk_posts_user
            references "user"
);

create index idx_posts_board_id
    on posts (board_id);

create table replies
(
    id         bigint generated by default as identity
        primary key,
    content    text,
    created_at timestamp default now(),
    is_liked   boolean,
    is_top     boolean,
    n_comments integer,
    n_likes    integer,
    post_id    bigint
        constraint fk_replies_posts
            references posts,
    update_at  timestamp default now(),
    user_id    bigint
        constraint fk_relies_user
            references "user"
);

create index idx_replies_post_id
    on replies (post_id);

create index idx_replies_user_id
    on replies (user_id);

create table comments
(
    id            bigint generated by default as identity
        primary key,
    content       text,
    created_at    timestamp default now(),
    is_liked      boolean,
    n_likes       integer,
    reply_id      bigint
        constraint fk_comments_reply
            references replies,
    reply_user_id bigint
        constraint fk_reply_user_user
            references "user",
    user_id       bigint
        constraint fk_comments_user_id
            references "user"
);

