//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::board::Entity as Board;
pub use super::comments::Entity as Comments;
pub use super::posts::Entity as Posts;
pub use super::replies::Entity as Replies;
pub use super::user::Entity as User;
